service: go-playground 

provider:
  name: aws
  runtime: go1.x
  lambdaHashingVersion: 20201221
  stackName: go-playground

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:

  hello-world:
    handler: bin/main
    # events:
    #   - http:
    #       path: hello
    #       method: post