service: go-playground 

provider:
  name: aws
  runtime: go1.x
  lambdaHashingVersion: 20201221
  stackName: go-playground

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:

  health:
    handler: bin/health
    events:
      - http:
          path: health
          method: get
      - http:
          path: health
          method: post