version: 2.1

orbs: 
  go: circleci/go@1.7.0
  node: circleci/node@4.7.0
  aws-cli: circleci/aws-cli@2.0.6

jobs:
  build:
    executor:
      name: go/default
      tag: '1.16'
    steps:
      - checkout
      - go/load-cache
      - go/mod-download
      - go/save-cache
      # - go/test:
      #     covermode: atomic
      #     failfast: true
      #     race: true

  deploy:
    executor: node/default
    steps:
      - checkout
      - node/install
      - run: node --version
      # - run: serverless deploy --stage ${CIRCLECI_BRANCH}

workflows:
  primary:
    jobs:
      - build
      - deploy
