version: 2.1

orbs: 
  go: circleci/go@1.7.0
  node: circleci/node@4.7.0
  aws-cli: circleci/aws-cli@2.0.6

jobs:
  lint:
    executor:
      name: go/default
      tag: '1.16'
    steps:
      - checkout
      - go/load-cache
      - go/mod-download
      - go/save-cache
      - run:
          name: Lint
          command: make lint
  build:
    executor:
      name: go/default
      tag: '1.16'
    steps:
      - checkout
      - go/load-cache
      - go/mod-download
      - go/save-cache
      - run:
          name: Build
          command: make build
      - persist_to_workspace:
          root: /home/circleci/project
          paths:
            - bin/* 
      - store_artifacts:
            path: bin

  test:
    executor:
      name: go/default
      tag: '1.16'
    steps:
      - checkout
      - go/load-cache
      - go/mod-download
      - go/save-cache
      - run:
          name: Coverage
          command: make cover 
      # - go/test:
      #     covermode: atomic
      #     failfast: true
      #     race: true
      # - store_test_results:
      #     path: coverage

  deploy:
    executor: node/default
    steps:
      - checkout
      - node/install-packages
      - attach_workspace:
          at: /home/circleci/project
      - run: node --version
      - run: node ./node_modules/serverless/bin/serverless deploy --stage ${CIRCLE_BRANCH}

workflows:
  primary:
    jobs:
      - lint
      - test
      - build
      - deploy:
          requires:
            - lint
            - test
            - build
          context: cuffney
